name: Zina Video Pipeline

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick ffmpeg xvfb libsm6 libxext6
          sudo sed -i 's/<policy domain="coder" rights="none" pattern="MVG" \/>/<!-- & -->/' /etc/ImageMagick-*/policy.xml

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest streamlit pytest-mock

      - name: Run integration test (headless)
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 640x480x16 &
          python test_integration.py --ci-mode
          ffprobe -v error test_output.mp4
          [ -f "test_output.mp4" ] || (echo "❌ Video file not created"; exit 1)

      - name: Test Streamlit app (headless)
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 &
          python -c "
          import os
          os.environ['CI'] = 'true'
          from video_viewer import generate_video
          assert generate_video() is True
          print('✅ Streamlit components verified')
          "

      - name: Run unit tests
        run: |
          pytest tests/ -v --cov=./ --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()